INTRODUCTION TO NUMPY


In [185]:
#Numpy array initiation
import numpy as np

a= np.array([1,2,3,4,5])
type(a)

numpy.ndarray

The data type of numpy is n-dimention array, where 'n' can be any interger number. But if n = 1; 1-dimension array, n=2; 2-dimention array, and if 'n' is equal to any number apart from 1 and 2 that is considered as a Tensor.

A tensor is an array with three dimension or higher

In [186]:
#Accessing element in array
#Index of elements in numpy array start from 0
#Let's access the first element of a
a[0]

1

In [187]:
#Second element and so on will be accessed the same
#i.e
a[4]

5

In [188]:
#We can create an array filled by Zero's and one's
a = np.zeros(3)
a

array([0., 0., 0.])

In [189]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [190]:
#Additionally, you can create an array whose initial content are random and depend on the state of the memory
a = np.empty(4)
a

array([2., 4., 6., 8.])

In [191]:
#Creating a range of elements in array
#we use numpy.arange(), its has three parameter; (start,end,step size)
a = np.arange(6)#It use a default, start = 0, step size = 1, end = number given minus one
a

array([0, 1, 2, 3, 4, 5])

In [192]:
a = np.arange(1,10,2)#start = 1, end = 10, step size = 2
a

array([1, 3, 5, 7, 9])

In [193]:
#We can use also numpy.linspace()
#'lin' refers to generating linearly spaced values as opposed to the sibling function logspace,
#which generates logarithmically spaced values
#To create an array with values that are spaced linearly in a specified interval
#Essentially,you specify a starting point and ending point of an interval,
#And then specify the total number of breakpoint you want within that interval(including the start point and end point)
a = np.linspace(1,10,5)#startpoint = 1, ending point = 10,number of breakpoint =5
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [194]:
#To know the shape,dimension and size of an array
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

'6' means a single row with 6 elements

In [195]:
a.ndim

1

'1' means 1-dimension array

In [196]:
a.size

6

'6' means an array have 6 element

In [197]:
#Let's try another example
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

'2' represent number of rows, '3' represent number of columns

In [198]:
a.ndim

2

'2' means 2-dimension array

In [199]:
#Size is the product of the element of the array's shape
a.size

6

'6' means an array have 6 elements

RESHAPING NUMPY ARRAY

In [200]:
#we use numpy.reshape() function
#When we use the reshape method,
#The array you want to produce needs to have the same number of elements as the original array

#i.e
a = np.arange(0,100,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [201]:
#number of elements in array
len(a)

20

In [202]:
#So if we want to reshape another array, the number of new array elements must be the same as origin array
b = a.reshape(4,5)#rows = 4, columns = 5;since the product of 4*5 = 20,hence the size = 20
b

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

Another examples are given below

In [203]:
c = a.reshape(10,2)
c

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [204]:
c.size

20

In [205]:
d = a.reshape(2,10)
d

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]])

In [206]:
d.size

20

ACCESSING ELEMENTS OF NUMPY ARRAY

In [207]:
#Indexing Numpy Array
#Accessing 1-dimension Numpy array elements
a = np.array([1,2,3,4,5])
a[4]

5

In [208]:
#Accessing 2-dimension Numpy array elements
#We use comma separated integers representing the dimension and the index of the element
a = np.array([[1,2,3],[4,5,6]])
a[1,0]#accesing 4

4

In [209]:
a[0,1]#accessing 2

2

In [210]:
#Accessing 3-dimension Numpy array elements
#To access elements in 3-dimension numpy array we can use comma separated integers representing the dimensions
#and the index of the elements

#i.e
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a[1,1,0]#accessing number 10



10

In accessing 3-dimension array i.e accessing number 10 in array 'a' we do a[1,1,0], where the first number represents the first dimension, the second number represents the second dimension, the third number represent represent the third dimension. So n-dimension array may be accessed in the same way starting from first dimension which is represented by the first number to the n-dimension which is represented by the last number i.e array[1,.............,n] where 'n' is number of dimension.

Consider more examples below;

In [211]:
#We combine different concept from the above illustration
b = np.array([[[np.arange(2,10,2)],[np.arange(10,20,3)]],[[np.zeros(4)],[np.empty(4)]]])
b

array([[[[ 2.,  4.,  6.,  8.]],

        [[10., 13., 16., 19.]]],


       [[[ 0.,  0.,  0.,  0.]],

        [[ 2.,  4.,  6.,  8.]]]])

Let's try to access different elements from the array 'b'

In [212]:
#Accessing 2.00000000e+000
b[0,0,0,0]

2.0

In [213]:
#Accessing 3.63632315e-321
b[1,1,0,2]

6.0

Try to test the rest for more understanding

In [214]:
#Negative indexing
#It access an array from the end
a = np.array([1,2,3,4,5,6])
a[-1]#access the last element

6

In [215]:
a[-2]#access the second element from the last

5

SLICING NUMPY ARRAY

-Slicing is an extracting a particular set of elements from your array.

-It syntax is [start:end:step]

-If we don't pass any of the given values for start, end and step they will default to the following values:

-start: default to 0

-end: default to the length of the array in the given dimension

-step: default to 1

In [216]:
#Slicing  1-Dimension array
a = np.array([1,2,3,4,5,6,7])
a[0:3]#accessing element from first element to third element

array([1, 2, 3])

NOTE: The result includes the start index,but excludes the end index

In [217]:
#More examples
a[0:7:2]#star = 0, end = 7, step = 2

array([1, 3, 5, 7])

In [218]:
a[0:7:1]

array([1, 2, 3, 4, 5, 6, 7])

In [219]:
a[4:]

array([5, 6, 7])

In [220]:
a[:-1]

array([1, 2, 3, 4, 5, 6])

In [221]:
a[-3:-1]

array([5, 6])

In [222]:
a[1:5:2]

array([2, 4])

In [223]:
#Slicing 2-Dimension Array
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
#From the second element,slice elements from index 1 to index 4(remember the last element is not included)
a[1,1:4]

array([7, 8, 9])

In [224]:
#Another example
#From both element return index 2
a[:,2]

array([3, 8])

In [225]:
#An alternative way
a[0:2,2]

array([3, 8])

In [226]:
#Another example
#From both elements, slice index 1 to index 4
a[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [227]:
#An alternative way
a[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

NUMPY OPERATIONS

-axis = 0 means row wise

-axis = 1 means column wise

1.SUMMING ELEMENTS IN ARRAY

In [228]:
#We use numpy.sum() where the axis parameter controls which axis will be aggregated
a = np.array([[0,1,2],[3,4,5]])
print("Axis 0 sum: {}".format(np.sum(a,axis = 0)))
print("Axis 1 sum: {}".format(np.sum(a,axis = 1)))


Axis 0 sum: [3 5 7]
Axis 1 sum: [ 3 12]


In [229]:
#Another examples
a = np.arange(100,1000)
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203,
       204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
       217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
       230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
       243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
       256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268,
       269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 28

In [230]:
len(a)

900

In [231]:
a.ndim

1

In [232]:
#Because array 'a' is 1-dimension array, to obtain a sum of element, axis parameter is not necessary to be used.
#axis =0 will give the same result as when axis parameter is not specified.
np.sum(a)

494550

In [233]:
np.sum(a,axis = 0)

494550

But when we pass axis = 1 will throw an error

In [234]:
b = a.reshape(180,5)
b

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154],
       [155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164],
       [165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174],
       [175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184],
       [185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194],
       [195, 196, 197, 198, 199],
       [200, 201, 202, 203, 204],
       [205, 206, 207, 208, 209],
       [210, 211, 212, 213, 214],
       [215, 216, 217, 218, 219],
       [220, 221, 222, 223, 224],
       [225, 226, 227, 228, 229],
       [230, 231, 232, 233, 234],
       [235, 236, 237, 238, 239],
       [240, 241, 242, 243, 244],
       [245, 2

In [235]:
b.shape

(180, 5)

In [236]:
b.ndim

2

In [237]:
b.size

900

In [238]:
np.sum(b, axis = 0)#summing row wise

array([98550, 98730, 98910, 99090, 99270])

In [239]:
np.sum(b,axis = 0).size

5

In [240]:
np.sum(b, axis = 1)#summing column wise

array([ 510,  535,  560,  585,  610,  635,  660,  685,  710,  735,  760,
        785,  810,  835,  860,  885,  910,  935,  960,  985, 1010, 1035,
       1060, 1085, 1110, 1135, 1160, 1185, 1210, 1235, 1260, 1285, 1310,
       1335, 1360, 1385, 1410, 1435, 1460, 1485, 1510, 1535, 1560, 1585,
       1610, 1635, 1660, 1685, 1710, 1735, 1760, 1785, 1810, 1835, 1860,
       1885, 1910, 1935, 1960, 1985, 2010, 2035, 2060, 2085, 2110, 2135,
       2160, 2185, 2210, 2235, 2260, 2285, 2310, 2335, 2360, 2385, 2410,
       2435, 2460, 2485, 2510, 2535, 2560, 2585, 2610, 2635, 2660, 2685,
       2710, 2735, 2760, 2785, 2810, 2835, 2860, 2885, 2910, 2935, 2960,
       2985, 3010, 3035, 3060, 3085, 3110, 3135, 3160, 3185, 3210, 3235,
       3260, 3285, 3310, 3335, 3360, 3385, 3410, 3435, 3460, 3485, 3510,
       3535, 3560, 3585, 3610, 3635, 3660, 3685, 3710, 3735, 3760, 3785,
       3810, 3835, 3860, 3885, 3910, 3935, 3960, 3985, 4010, 4035, 4060,
       4085, 4110, 4135, 4160, 4185, 4210, 4235, 42

In [241]:
np.sum(b,axis = 1).size

180

2.CONCATENATING NUMPY ARRAY

In [242]:
#We use numpy.concatenate()
a = np.array([[1,1,1],[1,1,1]])
b = np.array([[9,9,9],[9,9,9]])
row_wise = np.concatenate([a,b],axis = 0)
row_wise

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [243]:
column_wise = np.concatenate([a,b], axis = 1)
column_wise

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [244]:
#Another example
#Since its 1-dimension array
#We can specify the axis = 0 or not,
#but axis = 1 may throw an error
a = np.array([1,1,1])
b = np.array([9,9,9])
row_wise = np.concatenate([a,b])
row_wise

array([1, 1, 1, 9, 9, 9])

In [245]:
#Alternative
row_wise = np.concatenate([a,b],axis = 0)
row_wise

array([1, 1, 1, 9, 9, 9])

3.SORTING ARRAY

In [246]:
#We use np.sort()
#You can specify the axis,kind and order when you call the function
#By default it sort in ascending order
#An example
a = np.array([2,4,5,1,0,-1,-56,78,4,30])
np.sort(a)

array([-56,  -1,   0,   1,   2,   4,   4,   5,  30,  78])

In [247]:
#Another example
#Let's create a random numbers in array
a = np.random.random(10)
a

array([0.69780324, 0.43195692, 0.05284583, 0.24471311, 0.58741054,
       0.74536937, 0.4756511 , 0.15790835, 0.20727378, 0.33860359])

In [248]:
#Let's sort it in ascending order
np.sort(a)

array([0.05284583, 0.15790835, 0.20727378, 0.24471311, 0.33860359,
       0.43195692, 0.4756511 , 0.58741054, 0.69780324, 0.74536937])

4.MATHEMATICAL OPERATIONS IN ARRAY

Various mathematical operations may be performed on Numpy arrays.

In [249]:
#An Example 
#Finding the square roots of elements in numpy array
#We may use numpy.sqrt()
a = np.array([4,9,16])
b = np.sqrt(a)
b

array([2., 3., 4.])

In [250]:
#Finding a standard deviation of an array
#Use numpy.std()
np.std(b)

0.816496580927726

In [251]:
#Let's use chaining method
print("The result is the same.")
np.sqrt(a).std()

The result is the same.


0.816496580927726

In [252]:
#Another example
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,12,13],[7,9,0]])
print("sums is:\n{}".format((a+b)))
print("Difference is:\n{}".format((a-b)))
print("Product is:\n{}".format((a*b)))
print("Quotient is:\n{}".format((a/b)))

sums is:
[[11 14 16]
 [11 14  6]]
Difference is:
[[ -9 -10 -10]
 [ -3  -4   6]]
Product is:
[[10 24 39]
 [28 45  0]]
Quotient is:
[[0.1        0.16666667 0.23076923]
 [0.57142857 0.55555556        inf]]


C:\Users\user\AppData\Local\Temp\ipykernel_2376\2922813518.py:7: RuntimeWarning: divide by zero encountered in true_divide
  print("Quotient is:\n{}".format((a/b)))


This error is Due to division of Zero. Let's modify the element in order to avoid that error.


In [253]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,12,13],[7,9,2]])
print("Quotient is:\n{}".format((a/b)))

Quotient is:
[[0.1        0.16666667 0.23076923]
 [0.57142857 0.55555556 3.        ]]


In [254]:
#How to stack arrays in sequency vertically(row wise)
#We use numpy.vstack()
#An example
a = np.random.random(5)
a

array([0.57608856, 0.10402109, 0.81066866, 0.38602682, 0.07108804])

In [255]:
#Let's stack array in sequence vertically
np.vstack(a)

array([[0.57608856],
       [0.10402109],
       [0.81066866],
       [0.38602682],
       [0.07108804]])

In [256]:
#An alternative way
np.row_stack(a)

array([[0.57608856],
       [0.10402109],
       [0.81066866],
       [0.38602682],
       [0.07108804]])

In [257]:
#Another example
a = np.arange(-12,23,4)
a

array([-12,  -8,  -4,   0,   4,   8,  12,  16,  20])

In [258]:
b = np.linspace(10,100,9)
b

array([ 10.  ,  21.25,  32.5 ,  43.75,  55.  ,  66.25,  77.5 ,  88.75,
       100.  ])

In [259]:
#We combine and arrange it vertically
c = np.vstack([a,b])
c

array([[-12.  ,  -8.  ,  -4.  ,   0.  ,   4.  ,   8.  ,  12.  ,  16.  ,
         20.  ],
       [ 10.  ,  21.25,  32.5 ,  43.75,  55.  ,  66.25,  77.5 ,  88.75,
        100.  ]])

In [260]:
#dimension of 'c'
c.ndim

2

In [261]:
#How to stack arrays in sequency horizontally(column wise)
#We use numpy.hstack()
#An example
a = np.arange(1,18,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [262]:
a.size

9

In [263]:
a.shape

(9,)

In [264]:
b = a.reshape(3,3)
b

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [265]:
b.size

9

In [266]:
b.shape

(3, 3)

In [267]:
#Let's stack 'b' in sequence horizontally
#after stack 'b' horizontally the result will be the same as that in array 'a'
np.hstack(b)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [268]:
#It will continue...................
#More numpy function may be implemented..............